export const FETCH_POSTS = 'FETCH_POSTS';
export const FETCH_SINGLE_POST = 'FETCH_SINGLE_POST';
export const FETCH_USER_POSTS = 'FETCH_USER_POSTS';
export const NEW_POST = 'NEW_POST';

export const FETCH_SUBREDDITS = 'FETCH_SUBREDDITS';
export const FETCH_SUBREDDIT_POSTS = 'FETCH_SUBREDDIT_POSTS'

export const FETCH_COMMENTS = 'FETCH_COMMENTS';
export const FETCH_USER_COMMENTS = 'FETCH_USER_COMMENTS'
export const NEW_COMMENT = 'NEW_COMMENT';

export const RECEIVE_USER = 'RECEIVE_USER'
export const LOGOUT_USER = 'LOGOUT_USER'
































// export const IS_USER_AUTHENTICATED = 'IS_USER_AUTHENTICATED';
// export const DEAUTHENTICATE_USER = 'DEAUTHENTICATE_USER';
// export const CHECK_AUTHENTICATION_STATUS = 'CHECK_AUTHENTICATION_STATUS'
//
// export const CREATE_USER = 'CREATE_USER'
// export const ADD_USER = 'ADD_USER'
// export const REMOVE_USER = 'REMOVE_USER'
// export const CHECK_USER = 'CHECK_USER'
