export const FETCH_POSTS = 'FETCH_POSTS';
export const FETCH_SINGLE_POST = 'FETCH_SINGLE_POST';
export const FETCH_USER_POSTS = 'FETCH_USER_POSTS';
export const NEW_POST = 'NEW_POST';

export const FETCH_SUBREDDITS = 'FETCH_SUBREDDITS';
export const FETCH_SUBREDDIT_POSTS = 'FETCH_SUBREDDIT_POSTS'

export const FETCH_COMMENTS = 'FETCH_COMMENTS';
export const FETCH_USER_COMMENTS = 'FETCH_USER_COMMENTS'
export const NEW_COMMENT = 'NEW_COMMENT';
